name: DockerHubBuild
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker.io
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin;
    - name: Docker Build 
      run: |
        docker build . --file ./src/Dockerfile --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/ccio-openwrt-builder
    - name: Docker Tag Latest
      run: |
        docker tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/ccio-openwrt-builder ${{ secrets.DOCKERHUB_ORGANIZATION  }}/ccio-openwrt-builder
    - name: Docker Tag OpenWRT Version
      run: |
        docker tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/ccio-openwrt-builder ${{ secrets.DOCKERHUB_ORGANIZATION  }}/ccio-openwrt-builder:19.07.5
    - name: Docker Push docker.io
      run: |
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/ccio-openwrt-builder;                    \
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/ccio-openwrt-builder:19.07.5;
